spring:
  redis:
    host: redis
    port: 6379

aws:
  credentials:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    instanceProfile: true
  region:
    static: ${S3_REGION}
    auto: false
  s3:
    bucket: ${S3_BUCKET}
  stack:
    auto: false