spring:
  redis:
    host: redis
    port: 6379

aws:
  credentials:
    accessKey: ${S3_ACCESS_KEY}
    secretKey: ${S3_SECRET_KEY}
    instanceProfile: true
  region:
    static: ap-northeast-2
    auto: false
  s3:
    bucket: ${S3_BUCKET}
  stack:
    auto: false