version: '3'
services:

  spring-boot:
    container_name: api-server
    image: simmigyeong/depromeet7
    build:
      context: './Api'
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080