version: '3'

services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"

  api-server:
    image: simmigyeong/depromeet
    container_name: api-server
    build:
      context: './Api'
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - redis