spring:
  profiles:
    include:
      - domain
      - core
      - infrastructure
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
swagger:
  user: ${SWAGGER_USER:user}
  password: ${SWAGGER_PASSWORD:password}

sentry:
  dsn: ${DSN_KEY}
  enable-tracing: true

server:
  servlet:
    context-path: /api
  forward-headers-strategy: framework

client:
  kakao:
    clientId: ${KAKAO_CLIENT_ID}
    clientSecret: ${KAKAO_CLIENT_SECRET}
    redirectUri: ${KAKAO_REDIRECT_URI}
    localRedirectUri: ${KAKAO_LOCAL_REDIRECT_URI}
    authUrl: ${KAKAO_AUTH_URL}
    apiUrl: ${KAKAO_API_URL}

front:
  domain:
    local: ${LOCAL_FRONT_DOMAIN}
    server: ${FRONT_DOMAIN}