spring:
  profiles:
    include:
      - domain
      - core
      - infrastructure
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
swagger:
  user: ${SWAGGER_USER:user}
  password: ${SWAGGER_PASSWORD:password}

sentry:
  dsn: ${DSN_KEY}
  enable-tracing: true

server:
  servlet:
    context-path: /api
  forward-headers-strategy: framework

client:
  kakao:
    clientId: 87c4a522c16ebfb0908e31de14e71d26
    clientSecret: oRcPYEMM4U68DshJqhP1Iv2EkCtI5I2f
    redirectUri: https:/ding-dong-planet.com/auth/callback/kakao
    authUrl: https://kauth.kakao.com
    apiUrl: https://kapi.kakao.com